from __future__ import annotations

from image_toolbox.core.upscale_engines.types import UpscalePreset


UPSCALE_PRESETS = [
    UpscalePreset("photo_hd", "照片高清", "通用照片 4x 高清放大。", "realesrgan", "realesrgan-x4plus", 4),
    UpscalePreset("anime_art", "动漫插画", "动漫、插画和线条素材 4x 放大。", "realesrgan", "realesrgan-x4plus-anime", 4),
    UpscalePreset("conservative", "保守增强", "较保守的 4x 增强，减少过度锐化。", "realesrgan", "realesrnet-x4plus", 4),
    UpscalePreset("quick_preview", "快速预览", "使用 2x 快速查看效果。", "realesrgan", "realesrgan-x4plus", 2),
    UpscalePreset(
        "low_memory",
        "低显存稳定",
        "更保守的 Tile 设置，适合大图或显存较小的电脑。",
        "realesrgan",
        "realesrgan-x4plus",
        2,
        low_memory_mode=True,
        tile_mode="manual",
        tile_size=128,
    ),
    UpscalePreset(
        "waifu2x_line_art",
        "动漫线稿",
        "Waifu2x 线稿和干净插画 4x 增强。",
        "waifu2x",
        "anime_style_art",
        4,
        noise_level=1,
    ),
    UpscalePreset(
        "waifu2x_illustration",
        "动漫插画",
        "Waifu2x CUNet 插画 4x 增强，中等降噪。",
        "waifu2x",
        "cunet",
        4,
        noise_level=2,
    ),
    UpscalePreset(
        "waifu2x_restore",
        "动漫修复",
        "Waifu2x CUNet 插画 4x 修复，较强降噪。",
        "waifu2x",
        "cunet",
        4,
        noise_level=3,
    ),
    UpscalePreset(
        "realcugan_anime_hd",
        "动漫高清 Real-CUGAN",
        "Real-CUGAN SE 4x 高清增强，适合动漫插画。",
        "realcugan",
        "models-se",
        4,
        noise_level=0,
        syncgap_mode=2,
    ),
    UpscalePreset(
        "realcugan_restore",
        "动漫修复 Real-CUGAN",
        "Real-CUGAN PRO 4x 修复，线条和色块增强更强。",
        "realcugan",
        "models-pro",
        4,
        noise_level=3,
        syncgap_mode=2,
    ),
    UpscalePreset(
        "realcugan_preview",
        "动漫快速预览 Real-CUGAN",
        "Real-CUGAN SE 2x 快速预览。",
        "realcugan",
        "models-se",
        2,
        noise_level=0,
        syncgap_mode=3,
    ),
    UpscalePreset(
        "realcugan_low_memory",
        "低显存 Real-CUGAN",
        "Real-CUGAN SE 2x 低显存稳定模式。",
        "realcugan",
        "models-se",
        2,
        low_memory_mode=True,
        tile_mode="manual",
        tile_size=128,
        noise_level=0,
        syncgap_mode=2,
    ),
    UpscalePreset("realsr_photo_hd", "照片高清 RealSR", "RealSR DF2K 照片 4x 高清增强。", "realsr", "models-DF2K", 4),
    UpscalePreset(
        "realsr_jpeg_restore",
        "JPEG照片修复 RealSR",
        "RealSR DF2K_JPEG 压缩照片 4x 修复。",
        "realsr",
        "models-DF2K_JPEG",
        4,
    ),
    UpscalePreset(
        "srmd_old_photo_restore",
        "老图修复 SRMD",
        "SRMD 2x 去噪修复，适合老图和模糊图。",
        "srmd",
        "srmd",
        2,
        noise_level=2,
    ),
    UpscalePreset(
        "srmd_blur_enhance",
        "模糊图增强 SRMD",
        "SRMD 4x 增强，适合模糊图片。",
        "srmd",
        "srmd",
        4,
        noise_level=1,
    ),
    UpscalePreset("anime4k_quick", "动漫快速增强 Anime4K", "Anime4K 2x 快速轻量增强。", "anime4k", "default", 2),
]
